AllCops:
  TargetRubyVersion: 2.6

  # Include gemspec and Rakefile
  Include:
    - '**/*.gemspec'
    - '**/*.podspec'
    - '**/*.jbuilder'
    - '**/*.rake'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Capfile'
    - '**/Guardfile'
    - '**/Podfile'
    - '**/Thorfile'
    - '**/Vagrantfile'
  Exclude:
    - 'vendor/**/*'
    - 'stubs/**/*'
    - 'spec/support/shared_contexts/*'

# Checks formatting of special comments
CommentAnnotation:
  Keywords:
    - TODO
    - FIXME
    - OPTIMIZE
    - HACK
    - REVIEW

########################################
# Style Cops

Style/Documentation:
  Enabled: false

Style/FileName:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

########################################
# Lint Cops

Lint/Eval:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

########################################
# Metrics Cops

Metrics/LineLength:
  Max: 110

Metrics/MethodLength:
  CountComments: false # count full line comments?
  Max: 20

Metrics/ClassLength:
  Max: 120

Metrics/AbcSize:
  Max: 20
